sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
install:
- sudo add-apt-repository --yes ppa:avsm/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y opam
- opam init -y
- eval $(opam config env)
- opam config var root
- opam install -y ocamlfind ocamlgraph
- travis_wait opam install -y coq
- opam list
script:
- autoconf
- ./configure
- make
- make tests | tee tmp.log
- if grep DIFFERENCES tmp.log ; then for i in $(grep DIFFERENCES tmp.log | grep -o 'diff .*' | sed s'/diff //g' | sed s'/ /~/g'); do i="$(echo "$i" | sed s'/~/ /g')"; echo diff $i; diff $i; done ; fi
- if grep DIFFERENCES tmp.log ; then exit 1 ; else exit 0 ; fi
